language: python

python:
  - '2.7'

services:
  - postgresql

addons:
  postgresql: '9.4'

env:
  - GEOKEY='>=0.8,<0.9'

virtualenv:
  system_site_packages: true

install:
  - sudo rm /etc/apt/sources.list.d/ubuntugis-stable-source.list
  - sudo apt-get update -y
  - sudo apt-get install python-gdal gdal-bin binutils
  - export C_INCLUDE_PATH=/usr/include/gdal
  - export CPLUS_INCLUDE_PATH=/usr/include/gdal
  - pip install --upgrade pip

before_script:
  - psql template1 postgres -c 'create extension hstore;'
  - psql -c 'create database geokey;' -U postgres
  - psql -U postgres -d geokey -c 'create extension postgis;'
  - pip install geokey$GEOKEY
  - pip install -r travis/requirements.txt
  - pip install -e .
  - python travis/manage.py migrate

script:
  - coverage run --source=geokey_airquality travis/manage.py test geokey_airquality

after_success:
  - coveralls
