# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-09-19 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geokey_airquality', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airqualityfield',
            name='type',
            field=models.CharField(choices=[('results', '01. Results'), ('date_out', '02. Date out'), ('time_out', '03. Time out'), ('date_collected', '04. Date collected'), ('time_collected', '05. Time collected'), ('exposure_min', '06. Exposure time (min)'), ('distance_from_road', '07. Distance from the road'), ('height', '08. Height from ground'), ('site_characteristics', '09. Site characteristics'), ('additional_details', '10. Additional details'), ('made_by_students', '11. Diffusion tube made by students')], max_length=50),
        ),
    ]
